HW by Railina Galieva
AufarZakiev/CPP-2020-2021-HW11 pull request #4
Opened 2021-04-04 19:21 UTC by RaiRG

До победного искала ошибки в task2 и task3, но так и не нашла. Выдает системную ошибку (сигнал SIGSEV) в середине цикла. В Википедии написано  "Сигнал, посылаемый при обращении к несуществующей области памяти или при обращениях с нарушением прав доступа. " Я проходилась дебагером, он эту ошибку выдает в середине цикла, где никак не может быть обращения к несуществующей области памяти. Потом поняла, что дело бесполезное, потому что потоки уже запущены и ошибка могла произойти именно во время их выполнения...
Может быть, есть что-то очевидное, чего я просто не замечаю?

2021-04-05 14:29 UTC, AufarZakiev requested changes

2021-04-05 14:29 UTC, AufarZakiev commented on main.cpp
> +  std::lock_guard<std::mutex> guard(mutex);
Можно без мьютекса обойтись, если каждый поток будет записывать в заранее опредленную ячейку массива `sums`

2021-04-05 14:29 UTC, AufarZakiev commented on main.cpp
> +void multiplyElements(std::vector<int>& result, std::vector<int>& vect1, std::vector<int>& vect2, int start, int finish)
Для щенячьего восторга можно все передаваемые по ссылке массивы обяъявлять const, если они не изменяются

2021-04-05 14:29 UTC, AufarZakiev commented on main.cpp
> +    threads.push_back(
тут тоже можно было (как и в первом задании) обойтись std::async

2021-04-05 14:29 UTC, AufarZakiev commented on main.cpp
> +    sums[i] = std::async(multiplyAndGetSum, std::ref(v1), std::ref(v2), i * 100, (i + 1) * 100);
Тут, конечно, async использовать не комильфо. При его использовании предполагается, что при вызове `.get()` будет получено значение из потока без условий. Тут же идет явная привязка к notify() . Если отдать этот код другому человеку и не сказать об этом, то его прграмма будет зависать навечно

2021-04-05 14:29 UTC, AufarZakiev commented on main.cpp
> +  std::vector<int> multiplyResults;
Ошибка кроется здесь. У этого массива нулевой размер, а потом вы его передаете в ф-ию multiplyElements и обращаетесь к элементам, которых еще не существует.
SIGSERV - это классическая ошибка, да, она указывает на доступ к памяти, которую ОС нам не давала. Чаще всего - это, конечно, выход за пределы массива или обращение по невалидному указателю

2021-04-08 11:30 UTC, RaiRG commented on main.cpp
> +    sums[i] = std::async(multiplyAndGetSum, std::ref(v1), std::ref(v2), i * 100, (i + 1) * 100);
Не совсем понимаю, почему будет программа зависать навечно... Выполнение потоков происходит в момент, когда вызывается метод .get()?

2021-04-08 19:56 UTC, AufarZakiev approved these changes

2023-08-24 06:43 UTC, closed without merging